product_api.content:
  path: '/product_api'
  defaults:
    _controller: '\Drupal\product_api\Controller\ProductController::content'
    _title: 'Product API'
  requirements:
    _permission: 'access content'
